### ISSUE TITLE
Error: Onion requests not allowed

### ISSUE THREAD

**Issue by aphex3k** [dannydeezy/deezy-auto-earn#2]
Is this coming eventually, does it need socks proxy support is there a different reason for it not being allowed?

**Comment by dannydeezy** [comment]
this is referring to LnURL onion requests right?

**Comment by aphex3k** [comment]
yes

**Comment by dannydeezy** [comment]
this should do it
https://github.com/dannydeezy/deezy-auto-earn/pull/4

**Comment by dannydeezy** [comment]
> this should do it #4

@aphex3k I don't have a Tor LnURL to test with - any chance you do and want to test the PR ^

**Comment by aphex3k** [comment]
Yes, but it will have to wait until I get back home. I'll report back...

**Comment by aphex3k** [comment]
~~I made a booboo and have to wait 50 more blocks before I can try again...~~

Channel opened, waiting for the transaction fees to come down for confirmation

So far, opening a new channel and waiting for it to confirm seem to work as expected and unaffected by the change...

**Comment by aphex3k** [comment]
If posted my feedback in #4 directly...

**Comment by aphex3k** [comment]
With #4 resolved and if one installs LNbits to create LNURLps one could use the deezy-auto-earn script to get paid for looping in liquidity to the own node!

**Comment by dannydeezy** [comment]
> With #4 resolved and if one installs LNbits to create LNURLps one could use the deezy-auto-earn script to get paid for looping in liquidity to the own node!

indeed. the challenge is that their node needs to have the inbound liquidity available to accomplish this

**Comment by dannydeezy** [comment]
closed by #4
